sudo: required
dist: trusty

language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - libboost-all-dev
      - libcurl4-openssl-dev
      - cmake

script:
  - cd TriviaBot
  - cmake .
  - make