sudo: required
dist: trusty

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-5
      - gcc-5
      - libboost1.55-all-dev
      - libcurl4-openssl-dev
      - cmake

install: export CXX="g++-5" CC="gcc-5";

script:
  - cd TriviaBot
  - cmake .
  - make